"""Web Render Module for RSS Page"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional
import yaml
import logging

from config import cfg

logger = logging.getLogger(__name__)

# Template path
RSS_TEMPLATE_PATH = Path(__file__).parent / "templates" / "rss.html"

def load_rss_sources() -> List[Dict]:
    """Load RSS source config for frontend"""
    try:
        with open("config/rss_sources.yaml", "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
            return data.get("sources", [])
    except Exception as e:
        logger.error(f"Error loading RSS config: {e}")
        return []

def get_full_json_data(date: str) -> Optional[List[Dict]]:
    """Try to load full JSON data generated by aggregator"""
    json_path = cfg.data_dir / f"{date}_full.json"
    if json_path.exists():
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                return data.get("sources", [])
        except Exception as e:
            logger.error(f"Error loading full JSON {json_path}: {e}")
    return None

def render_rss_page(date: str | None = None) -> str:
    """Render RSS feed page"""
    from .render import parse_markdown, get_available_dates
    
    available_dates = get_available_dates()
    if not available_dates:
        return "No data available"
        
    date_to_use = date or available_dates[0]
    
    # Try to get full JSON data first (richer content with descriptions)
    full_data = get_full_json_data(date_to_use)
    
    if full_data:
        all_sources = full_data
    else:
        # Fallback to Markdown parsing (might miss descriptions)
        logger.info(f"Full JSON not found for {date_to_use}, falling back to MD parsing")
        parsed = parse_markdown(date_to_use)
        all_sources = parsed["sources"]

    # Filter RSS sources
    rss_configs = load_rss_sources()
    rss_names = {s["name"] for s in rss_configs} # Match by name
    
    rss_data_sources = []
    
    for source in all_sources:
        # Match by name
        if source.get("name") in rss_names:
             # Enrich with config info (e.g. language)
             conf = next((s for s in rss_configs if s["name"] == source["name"]), {})
             source["config"] = conf
             
             # Ensure 'url' field exists (Markdown parser uses 'link')
             if source.get("items"):
                 for item in source["items"]:
                     if "link" in item and "url" not in item:
                         item["url"] = item["link"]
             
             rss_data_sources.append(source)
             
    # Prepare data for template
    data = {
        "selected_date": date_to_use,
        "sources": rss_data_sources,
        "build_time": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    
    template_text = RSS_TEMPLATE_PATH.read_text(encoding="utf-8")
    json_data = json.dumps(data, ensure_ascii=False, indent=2)
    html_content = template_text.replace("__RSS_DATA__", json_data)
    
    return html_content
